[tool.poetry]
name = "download-vertical-profiles"
version = "0.5.0"
description = "Download .map, .vmr and .mod files from ccycle.gps.caltech.edu"
authors = [
    "Marlon Mueller <marlon.mueller@tum.de>",
    "Moritz Makowski <moritz.makowski@tum.de>",
    "Xinxu Zhao <xinxu.zhao@tum.de>",
    "Florian Dietrich <flo.dietrich@tum.de>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
requests = "^2.28.1"
rich = "^12.6.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
mypy = "^0.991"
types-requests = "^2.28.11.5"

[tool.black]
line-length = 100

[tool.mypy]
strict = true
implicit_reexport = true