[tool.poetry]
name = "download-map-data"
version = "0.1.1"
description = ""
authors = [
    "Florian Dietrich <flo.dietrich@tum.de>",
    "Xinxu Zhao <xinxu.zhao@tum.de>",
    "Moritz Makowski <moritz.makowski@tum.de>"
]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.3.0"
Cerberus = "^1.3.4"
tenacity = "^8.0.1"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
