[tool.poetry]
name = "download-vertical-profiles"
version = "0.5.0"
description = "Download .map, .vmr and .mod files from ccycle.gps.caltech.edu"
authors = [
    "Florian Dietrich <flo.dietrich@tum.de>",
    "Xinxu Zhao <xinxu.zhao@tum.de>",
    "Moritz Makowski <moritz.makowski@tum.de>",
    "Marlon Müller <marlon.mueller@tum.de>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.0"
attrs = "^22.1.0"
filelock = "^3.8.0"


[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
black = "^22.10.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 95

[tool.mypy]
strict = true
implicit_reexport = true