[tool.poetry]
name = "download-vertical-profiles"
version = "0.3.0"
description = "download .map and .mod files ccycle.gps.caltech.edu"
authors = [
    "Florian Dietrich <flo.dietrich@tum.de>",
    "Xinxu Zhao <xinxu.zhao@tum.de>",
    "Moritz Makowski <moritz.makowski@tum.de>"
]

[tool.poetry.dependencies]
python = "3.9"
rich = "10.16.2"
Cerberus = "1.3.4"
tenacity = "8.0.1"

[tool.poetry.dev-dependencies]
black = "21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
