[tool.poetry]
name = "download-vertical-profiles"
version = "0.5.0"
description = "Download vertical profiles (GGG2014 and GGG2020) from ccycle.gps.caltech.edu"
authors = [
    "Marlon Mueller <marlon.mueller@tum.de>",
    "Moritz Makowski <moritz.makowski@tum.de>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
requests = "^2.28.1"
rich = "^12.6.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
mypy = "^0.991"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
types-requests = "^2.28.11.5"

[tool.black]
line-length = 100

[tool.mypy]
strict = true
implicit_reexport = true